---
name: "express"
priority: 0
version: "^4.17.1"
part_files:
  - part.ts.template
dependencies:
  - external - body-parser[bodyParser] ^1.19.0
  - external - http-status-codes[StatusCodes] ^2.1.4 noinclude
  - external dev @types/express ^4.17.13
additional_files:
  - api_root.ts.template as src/web/api.ts
  - V1Router.ts.template as src/web/v1/V1Router.ts
additional_imports:
  - import { StatusCodes } from "http-status-codes";
  - import apiRouter from "./web/api";
cross_template_replacements:
  commander_additional_optargs:
    - ".option(\"-p, --port <port>\", \"the port to run the webserver on\", CommanderUtils.parseAsInt, parseInt(process.env.PORT ?? \"8080\"))"
  dotenv_additional_env:
    - "PORT=8080"
