---
name: "commander"
priority: 0
version: "^8.0.0"
dependencies:
  - external - fs-extra[fs] ^10.0.0
  - external dev @types/fs-extra ^9.0.12
  - builtin - path
part_files:
  - part.ts.template
additional_files:
  - CommanderUtils.ts.template as src/utils/CommanderUtils.ts
additional_imports:
  - import * as CommanderUtils from "./utils/CommanderUtils";
