---
name: "commander"
priority: 0
version: "^8.0.0"
dependencies:
  - external - fs-extra[fs] ^10.0.0
  - external dev @types/fs-extra ^9.0.12 noinclude
  - builtin - path
part_files:
  - part.ts.template
additional_imports:
  - import { Command, OptionValues } from "commander";
