---
name: "eslint"
priority: 0
no_default_include: true
version: "^7.26.0"
dependencies:
  - external dev @typescript-eslint/parser ^4.22.1
  - external dev @typescript-eslint/eslint-plugin ^4.22.1
additional_files:
  - .eslintignore.template
  - .eslintrc.json.template
